### ISSUE TITLE
Movie DB select query

### ISSUE THREAD

**Issue by djvalley** [kbestul2/cvtc-agile-group-project#1]
I have a query to access the movies database that will replace the ContentRating column with the correct data retrieved out of the ratings table. 
ContentRating will return a string.
UserRating will return a float type.

```
SELECT Name, ReleaseDate, StreamDate, ratings.Rating AS ContentRating, Length, Description, UserRating, CoverImgUrl, TrailerKey, Platform FROM StreamLINE.movies
	INNER JOIN ratings USING (RatingID)
```
NOTE* there are 2 ratings columns currently, I named them ContentRating for like PG/PG-13/etc and there will be UserRating for when we implement a rating system.

**Comment by kbestul2** [comment]
I was wondering why there were two ratings fields. Fixed.
